export enum SpecificFieldType {
  integer = 'integer',
  number = 'number',
  address = 'address',
  email = 'email',
  url = 'url',
  rtf = 'rtf',
  money = 'money',
  percentage = 'percentage',
  date = 'date',
  enum = 'enum',
  string = 'string',
  password = 'password',
  table = 'table',
  optiongroup = 'optiongroup',
  radiogroup = 'radiogroup',
  boolean = 'boolean',
}
